version: "3.7"

services:
    nginx:
        restart: always
        build:
            context: "./nginx"
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./nginx/log:/var/log/nginx/
        ports:
            - "8080:8080"
            # - "443:443"
            # - "443:443/udp"
            # - "8443:8443"

        networks:
            - gate-tier

    mongodb:
        command: 
            - '--logpath'
            - '/var/log/mongodb/mongod.log'
        build:
            context: "./mongodb"
        logging:
            driver: none
        restart: always
        volumes:
            - ./mongodb/data:/data/db
        networks:
            - gate-tier

    backend:
        restart: always
        # ports:
        #     - "8080:8080"
        command: "yarn run deploy"
        environment: 
            MONGODB_IP: mongodb
            PORT: "8080"
            # FRONTEND_PORT: "80"
        build:
            context: "./packages/backend"
        volumes:
            - ./packages/backend/:/app/
            # because in leran project, the node_modules is location in root path
            - ./node_modules/:/app/node_modules/
            - /app/static/
        networks:
            - gate-tier
networks:
    gate-tier:
