version: "3.7"

services:
    nginx:
        restart: always
        build:
            context: "./nginx"
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./nginx/log:/var/log/nginx/
            - ./packages/frontend/dist/:/var/www/app/
        ports:
            - "80:80"
            - "8080:8080"
        networks:
            - gate-tier

    mongodb:
        command: 
            - '--logpath'
            - '/var/log/mongodb/mongod.log'
        build:
            context: "./mongodb"
        logging:
            driver: none
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: ewqewq
        volumes:
            - ./mongodb/data:/data/db
        networks:
            - gate-tier

    backend:
        restart: always
        command: "yarn run deploy"
        environment: 
            MONGODB_IP: mongodb
            PORT: "8080"
            FRONTEND_PORT: "80"
        build:
            context: "./packages/backend"
        volumes:
            - ./packages/backend/:/app/
            # because in leran project, the node_modules is location in root path
            - ./node_modules/:/app/node_modules/
            - /app/static/
        networks:
            - gate-tier
networks:
    gate-tier:
