version: 2.1
orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@2.2.0

jobs:
  install-docker:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - docker/install-docker
      - setup_remote_docker:
          version: 20.10.14
      - run:
          command: docker -v
          name: test docker
      - run:
          command: docker-compose -v
          name: test docker compose
      - run:
          command: pwd
          name: run docker
  build-and-deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn bootstrap
          name: Run bootstrap
      - run:
          command: yarn build
          name: Build app

workflows:
  test_my_app:
    jobs:
      - install-docker
      - build-and-deploy
