version: 2.1
orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@2.2.0

jobs:
  build-and-deploy:
    executor: node/default
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - docker/install-docker
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn bootstrap
          name: Run bootstrap
      - run:
          command: yarn build
          name: Build app

workflows:
  test_my_app:
    jobs:
      - build-and-deploy
