orbs:
  ansible-playbook: orbss/ansible-playbook@0.0.5

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - ansible-playbook/playbook:
          playbook: ansible/motd_playbook.yaml 

workflows:
  example-workflow:
    jobs:
      - example-job