version: 2.1
orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@2.2.0

jobs:
  # install-docker:
  #   docker:
  #     # replace with your preferred image
  #     - image: cimg/base:stable
  #   steps:
  #     - docker/install-docker
  #     - setup_remote_docker:
  #         version: 20.10.14
  #     - run:
  #         command: docker -v
  #         name: test docker
  #     - run:
  #         command: docker-compose -v
  #         name: test docker compose
  build-and-deploy:
    executor: node/default

    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - docker/install-docker
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn bootstrap
          name: Run bootstrap
      - run:
          command: yarn build
          name: Build app
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large

workflows:
  test_my_app:
    jobs:
      # - install-docker
      - build-and-deploy
