version: 2.1
orbs:
  docker: circleci/docker@2.2.0

jobs:
  build-and-deploy:
    docker:
      # replace with your preferred image
      - image: kajws/hue-controller
    steps:
      - docker/install-docker
      - setup_remote_docker:
          version: 20.10.14

workflows:
  test_my_app:
    jobs:
      - build-and-deploy
