version: 2.1
orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@2.2.0

jobs:
  my-job:
    docker:
      - image: kajws/hue-controller
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference


workflows:
  test_my_app:
    jobs:
      - my-job
