---
- hosts: vultr
  user: root
  gather_facts: False
  tasks:
    - name: install certbot
      apt:
        pkg:
          - certbot
        state: latest
        update_cache: true

    - name: copy cert key file
      command:
        chdir: /root
        cmd: echo 'y' | certbot certonly --standalone --agree-tos --redirect -m pengliheng111@gmail.com -d chat1.plhh.xyz
