---
- hosts: aws
  user: root
  gather_facts: False
  tasks:
    - name: Get running containers
      docker_host_info:
        containers: yes
      register: docker_info
    - name: Stop running containers
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ docker_info.containers | map(attribute='Id') | list }}"
    - name: Delete content & directory
      file:
        state: absent
        path: ~/chatroom/
    - name: pull latest code on develop branch
      git:
        repo: https://github.com/plh2/chatroom.git
        dest: ~/chatroom
        force: true
        version: develop

    - name: copy cert key file
      copy:
        src: /etc/letsencrypt/live/plhh.link/privkey.pem
        dest: ~/chatroom/nginx/cert/privkey.pem
        remote_src: yes
    - name: copy cert key file
      copy:
        src: /etc/letsencrypt/live/plhh.link/fullchain.pem
        dest: ~/chatroom/nginx/cert/fullchain.pem
        remote_src: yes

    - name: install dependences
      command:
        cmd: yarn run bootstrap
        chdir: ~/chatroom

    - name: build
      command:
        chdir: ~/chatroom
        cmd: npm run build

    - name: deploy
      command:
        chdir: ~/chatroom
        cmd: npm run deploy
