---
- hosts: vultr
  user: root
  gather_facts: False
  tasks:
    - name: Stop running containers
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ docker_info.containers | map(attribute='Id') | list }}"
    - name: Delete content & directory
      file:
        state: absent
        path: /root/chatroom/
    - name: pull latest code on develop branch
      git:
        repo: https://github.com/plh2/chatroom.git
        dest: /root/chatroom
        force: true
        version: develop

    - name: copy cert key file
      copy:
        src: /etc/letsencrypt/live/chat.plhh.xyz/privkey.pem
        dest: /root/chatroom/nginx/cert/privkey.pem
        remote_src: yes
    - name: copy cert key file
      copy:
        src: /etc/letsencrypt/live/chat.plhh.xyz/fullchain.pem
        dest: /root/chatroom/nginx/cert/fullchain.pem
        remote_src: yes

    - name: install dependences
      command:
        cmd: yarn run bootstrap
        chdir: /root/chatroom

    - name: build
      command:
        chdir: /root/chatroom
        cmd: npm run build

    - name: deploy
      command:
        chdir: /root/chatroom
        cmd: npm run deploy
