---
- hosts: ubuntu-test
  user: root
  gather_facts: False
  tasks:
    - name: pull latest code on develop branch
      git:
        repo: https://github.com/plh2/chatroom.git
        dest: ~/chatroom
        force: true
        version: develop

    - name: install dependences
      command:
        cmd: yarn run bootstrap
        chdir: ~/chatroom

    - name: build
      command:
        chdir: ~/chatroom
        cmd: npm run build

    - name: deploy
      command:
        chdir: ~/chatroom
        cmd: npm run deploy
...
