---
- hosts: vultr
  user: root
  gather_facts: False
  tasks:
    - name: pull latest code on develop branch
      git:
        repo: https://github.com/plh2/chatroom.git
        dest: /root/chatroom
        force: true
        version: develop

    - name: copy cert key file
      command:
        chdir: /root/chatroom
        cmd: cat /etc/letsencrypt/live/chat1.plhh.xyz/privkey.pem > nginx/cert/privkey.pem
    - name: copy cert key file
      command:
        chdir: /root/chatroom
        cmd: cat /etc/letsencrypt/live/chat1.plhh.xyz/fullchain.pem > nginx/cert/fullchain.pem

    - name: install dependences
      command:
        cmd: yarn run bootstrap
        chdir: /root/chatroom

    - name: build
      command:
        chdir: /root/chatroom
        cmd: npm run build

    - name: rm container
      command:
        chdir: /root/chatroom
        cmd: npm run down

    - name: deploy
      command:
        chdir: /root/chatroom
        cmd: npm run deploy
