---
- hosts: aws
  # user: ubuntu
  # gather_facts: False
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: Get running containers
      docker_host_info:
        containers: yes
      register: docker_info

    - name: Stop running containers
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ docker_info.containers | map(attribute='Id') | list }}"
    - name: Delete content & directory
      file:
        state: absent
        path: ~/chatroom/
    - name: Clone Repository
      git:
        repo: https://github.com/plh2/chatroom.git
        dest: ~/chatroom
        clone: yes
        update: yes
        version: develop

    - name: install certbot
      apt:
        pkg:
          - certbot
        state: latest
        update_cache: true
    - name: create cert key
      command:
        cmd: certbot certonly --standalone --agree-tos --redirect -m pengliheng111@gmail.com -d plhh.link -n

    - name: copy cert key file
      copy:
        src: /etc/letsencrypt/live/plhh.link/privkey.pem
        dest: ~/chatroom/nginx/cert/privkey.pem
        remote_src: yes
    - name: copy cert key file
      copy:
        src: /etc/letsencrypt/live/plhh.link/fullchain.pem
        dest: ~/chatroom/nginx/cert/fullchain.pem
        remote_src: yes
    - name: install dependences
      command:
        cmd: npm install
        chdir: ~/chatroom
    - name: build
      command:
        chdir: ~/chatroom
        cmd: npm run build
    - name: deploy
      command:
        chdir: ~/chatroom
        cmd: npm run deploy
...
