name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: List files in the repository
        run: |
          cd ansible &&  ansible-playbook playbook.yml
      # - name: Play Ansible Playbook
      #   uses: arillso/action.playbook@master
      #   with:
      #     playbook: ansible/playbook.yml
      #     inventory: ansible/hosts
      #   env:
      #     ANSIBLE_HOST_KEY_CHECKING: 'true'
      #     ANSIBLE_DEPRECATION_WARNINGS: 'true'
