name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Play Ansible Playbook
        uses: arillso/action.playbook@master
        with:
          playbook: ansible/playbook.yml
          inventory: ansible/hosts
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'true'
          ANSIBLE_DEPRECATION_WARNINGS: 'true'
