name: GitHub Actions CICD
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - 'develop'
jobs:
  Ansible-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          name: id_rsa-target
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: ssh-keyscan -H ${{ secrets.SSH_HOST }}
          config: |
            Host ubuntu-test
              HostName ${{ secrets.SSH_HOST }}
              User root
              IdentityFile ~/.ssh/id_rsa-target

      - name: run ansible
        run: |
          cd ansible && ansible-playbook cicd.yml
